[project]
name = "drgat"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch==2.7.0",
    "torch-geometric==2.3.1",
    "numpy==1.26.4",
    "matplotlib",
    "pandas==2.2.2",
    "jupyter",
    "ipykernel"
]
