name: Python Code Formatting

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.ipynb'

jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort nbqa
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Format code
      run: |
        black .
        isort .
        nbqa black .
        nbqa isort .
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: Apply auto-formatting"
        branch: ${{ github.head_ref }}
